version: '3.4'


services:

  djangovul:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: djangovul
    volumes:
      - /vulnpy:/vulnpy
    environment:
      DEBUG: 1
      AUTO_CREATE_PROJECT: 1
      PROJECT_NAME: ${PROJECT_NAME:-Python-Vulnpy-Django}
      PROJECT_VERSION: ${PROJECT_VERSION:-v1.2.0}
      ENGINE_NAME: ${ENGINE_NAME:-github-vul-test-django}
    expose:
      - "3020"