
name: Vul Test

on:
  push:
    branches:
      - jinghao1-patch-1
  pull_request:
    branches:
      - jinghao1-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Clone Vul Repository
        uses: actions/checkout@v2
        with:
          repository: HXSecurity/DongTai-agent-python
          ref: master
          path: DongTai-agent-python
      - name: Prepare Agent Config
        shell: python
        run: |
          import json
          example_filename = '${{ github.workspace }}/DongTai-agent-python/dongtai_agent_python/config-example.json'
          filename = '${{ github.workspace }}/config.json'
          with open(example_filename) as f:
              data = json.load(f)
          data['iast']['server']['token'] = '17d469cb3a7c32f2e6e71cfaafa5efc1871e492e'
          data['iast']['server']['url'] = 'https://iast-test.huoxian.cn/openapi'
          with open(filename, 'w') as f:
              json.dump(data, f)
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Run Vul Container
        env:
          PROJECT_VERSION: 'v1.2.${{ github.run_id }}'
        run: |
          pwd
          cd ${{ github.workspace }}
          ls
          docker-compose up -d
          docker-compose logs -f

      - name: Run Vul test
        run: |
          curl --fail --retry-delay 10 --retry 30 --retry-connrefused http://127.0.0.1:3020/vulnpy/cmdi/os-system/?user_input=ls
          bash ${{ github.workspace }}/tests/vul-test.sh http://127.0.0.1:3020


