
name: Vul Test

on:
  push:
    branches:
      - jinghao1-patch-1
  pull_request:
    branches:
      - jinghao1-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Vul Container
        env:
          PROJECT_VERSION: 'v1.2.${{ github.run_id }}'
        run: |
          pwd
          cd ${{ github.workspace }}
          ls
          docker-compose up -d

      - name: Run Vul test
        run: |
          curl --fail --retry-delay 10 --retry 30 --retry-connrefused http://127.0.0.1:3020/vulnpy/cmdi/os-system/?user_input=ls
          bash ${{ github.workspace }}/tests/vul-test.sh http://127.0.0.1:3020


