
name: Vul Test

on:
  push:
    branches:
      - jinghao1-patch-1
  pull_request:
    branches:
      - jinghao1-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Vul Container
        env:
          PROJECT_VERSION: 'v1.2.${{ github.run_id }}'
        run: |
          cd {{ github.run_id }}/vulnpy
          docker-compose up -d

      - name: Run Vul test
        run: |
          bash {{ github.run_id }}/vulnpy/tests/vul-test.sh

